matrix:
        include:
                - os: osx
                        env:
                                - MATRIX_EVAL="echo"
                - os: linux
                        env:
                                - MATRIX_EVAL="echo"

before_install:
        - eval "${MATRIX_EVAL}"
  
language: generic
script:
        - make run
