name: CI to build and run all samples
on: [push]
jobs: 
  CI-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting tests"
      - name: Checking out repository
        uses: actions/checkout@v2
      - run: make -C ${{ github.workspace }} run
      - run: echo "Tests completed"
